apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  type: LoadBalancer
  ports:
  - name: "vote-service"
    port: 5000          # This is the port exposed by the LoadBalancer
    targetPort: 5000    # This should match the container port where the app is running
  selector:
    app: vote           # Ensures that the service targets pods with the "app: vote" label
